--Criando uma view
CREATE VIEW VW_PEDIDOS_POR_CLIENTE
AS
SELECT TOP 10 * FROM [dbo].[TB_ACT_OLIST_CUSTOMER] as C
INNER JOIN [dbo].[TB_ACT_OLIST_ORDERS] as O 
ON C.CUSTOMER_ID = O.ORDER_CUSTOMER_ID
WHERE O.ORDER_STATUS = 'delivered'


--Alterando uma View
ALTER VIEW VW_PEDIDOS_POR_CLIENTE
AS
SELECT TOP 10 * FROM [dbo].[TB_ACT_OLIST_CUSTOMER] as C
INNER JOIN [dbo].[TB_ACT_OLIST_ORDERS] as O 
ON C.CUSTOMER_ID = O.ORDER_CUSTOMER_ID
WHERE O.ORDER_STATUS = 'invoiced'

SELECT * FROM VW_PEDIDOS_POR_CLIENTE